name: shell_lite
description: "Modern, lightweight, cross-platform SSH client & terminal emulator for iOS, Android, Linux, and Web."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  dartssh2: ^2.11.0
  xterm: ^4.0.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.5.5
  provider: ^6.1.2
  uuid: ^4.5.1
  pinenacl: ^0.6.0
  crypto: ^3.0.3
  local_auth: ^2.3.0
  web_socket_channel: ^3.0.3
  file_picker: ^11.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: JetBrains Mono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/JetBrainsMono-Italic.ttf
          style: italic
        - asset: assets/fonts/JetBrainsMono-BoldItalic.ttf
          weight: 700
          style: italic

