name: shell_lite
description: "Modern, lightweight, cross-platform SSH client & terminal emulator for iOS, Android, Linux, and Web."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartssh2: ^2.11.0
  xterm: ^4.0.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  uuid: ^4.5.1
  pinenacl: ^0.6.0
  crypto: ^3.0.3
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
