import 'dart:convert';
import 'package:flutter_test/flutter_test.dart';
import 'package:shell_lite/models/auth_method.dart';
import 'package:shell_lite/models/server_profile.dart';

void main() {
  group('ServerProfile', () {
    test('Default port is 22', () {
      final p = ServerProfile(
        displayName: 'Dev Box',
        host: '192.168.1.10',
        username: 'root',
        authMethod: const PasswordAuth(credentialTag: 'tag-1'),
      );
      expect(p.port, 22);
    });

    test('Custom port is preserved', () {
      final p = ServerProfile(
        displayName: 'Custom Port',
        host: 'example.com',
        port: 2222,
        username: 'admin',
        authMethod: const PasswordAuth(credentialTag: 'tag-2'),
      );
      expect(p.port, 2222);
    });

    test('Password auth JSON round-trip', () {
      final original = ServerProfile(
        displayName: 'Web Server',
        host: '10.0.0.1',
        port: 22,
        username: 'ubuntu',
        authMethod: const PasswordAuth(credentialTag: 'cred-abc'),
      );
      final jsonStr = json.encode(original.toJson());
      final decoded = ServerProfile.fromJson(json.decode(jsonStr) as Map<String, dynamic>);

      expect(decoded.displayName, original.displayName);
      expect(decoded.host, original.host);
      expect(decoded.port, original.port);
      expect(decoded.username, original.username);
      expect(decoded.authMethod, isA<PasswordAuth>());
      expect((decoded.authMethod as PasswordAuth).credentialTag, 'cred-abc');
      expect(decoded, original);
    });

    test('SSHKey auth JSON round-trip', () {
      final original = ServerProfile(
        displayName: 'Bastion',
        host: 'bastion.internal',
        port: 22,
        username: 'ops',
        authMethod: const SSHKeyAuth(privateKeyTag: 'key-xyz'),
      );
      final jsonStr = json.encode(original.toJson());
      final decoded = ServerProfile.fromJson(json.decode(jsonStr) as Map<String, dynamic>);

      expect(decoded.authMethod, isA<SSHKeyAuth>());
      expect((decoded.authMethod as SSHKeyAuth).privateKeyTag, 'key-xyz');
      expect(decoded, original);
    });

    test('Equality and HashCode', () {
      final p1 = ServerProfile(
        id: '00000000-0000-0000-0000-000000000001',
        displayName: 'A',
        host: 'a.com',
        username: 'u',
        authMethod: const PasswordAuth(credentialTag: 't1'),
      );
      final p2 = ServerProfile(
        id: '00000000-0000-0000-0000-000000000001',
        displayName: 'A',
        host: 'a.com',
        username: 'u',
        authMethod: const PasswordAuth(credentialTag: 't1'),
      );
      expect(p1, equals(p2));
      expect(p1.hashCode, equals(p2.hashCode));
    });

    test('Unique IDs generated by default', () {
      final p1 = ServerProfile(
        displayName: 'A',
        host: 'a',
        username: 'u',
        authMethod: const PasswordAuth(credentialTag: 't'),
      );
      final p2 = ServerProfile(
        displayName: 'A',
        host: 'a',
        username: 'u',
        authMethod: const PasswordAuth(credentialTag: 't'),
      );
      expect(p1.id, isNot(equals(p2.id)));
    });

    test('Initial command defaults to null', () {
      final p = ServerProfile(
        displayName: 'Test',
        host: 'localhost',
        username: 'root',
        authMethod: const PasswordAuth(credentialTag: 'x'),
      );
      expect(p.initialCommand, isNull);
    });

    test('Initial command JSON round-trip', () {
      final original = ServerProfile(
        displayName: 'Test',
        host: 'localhost',
        username: 'root',
        authMethod: const PasswordAuth(credentialTag: 'x'),
        initialCommand: 'tmux attach || tmux new',
      );
      final jsonStr = json.encode(original.toJson());
      final decoded = ServerProfile.fromJson(json.decode(jsonStr) as Map<String, dynamic>);

      expect(decoded.initialCommand, 'tmux attach || tmux new');
      expect(decoded, original);
    });
  });
}
