name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  ci-build:
    name: CI
    uses: ./.github/workflows/build-ios.yml
    with:
      upload_artifact: false
